### ISSUE TITLE
Documentation update?

### ISSUE THREAD

**Issue by ur7x** [hulkhaugen/hass-bha-icons#29]
Any chance the the documentation could be updated to match the new version?
I did the manual install and while the system still works (BHA icons are working), it does not "auto display" the icons which is the purpose of the new version

Also not sure how to use generate_js.py is this to be installed in HA? is it needed for the new version or is it stand alone code? 

Thanks  Love this plugin!

**Comment by hulkhaugen** [comment]
Installation has not changed, just a small part of the plugin which enables the icon picker in the UI, if that's what you mean by "auto display". If that's not enabled for you, it's probably because you have the older plugin loaded and not refreshed in your browsers cache. Alternatively, if you use an older version of HA where the Icon Picker isn't implemented yet.

The `generate_js.py` is just a tool made for me to automatically generate the plugin(js) with the svg files in the svg folder. The only file you need is [hass-bha-icons.js](https://github.com/hulkhaugen/hass-bha-icons/blob/master/dist/hass-bha-icons.js)
